#%RAML 1.0
title: TWARecurting API
description:
version: V1
baseUri: http://api.bronzesword.com/teacher-admin-web/

/mentors
  get:
    responses:
      200:
        body:
          application/json:
            mentorList
              properties:
                []:
                  properties:
                    mentorId:integer
                    mentorName:string
      500:
        description:服务器错误

/mentors/:mentorId
  get:
    responses:
      200:
        body:
          application/json
            mentorId:integer
            name:string
            e-mail:string
            skills
              properties:
                []
      500:
        description:服务器错误

  post:
    body:
      application/json:
        studentId:integer
    responses:
      201:
        description:添加成功
      500:
        description:服务器失败

/students
  get:
    responses:
      200:
        body:
          application/json:
            studentList
              properties:
                []:
                  properties:
                    studentId:integer
                    name:string
                    school:string
                    major:string

      500：
        description:服务器错误

/students/:studentId
  get:
    responses:
      200:
        body:
          application/json:
            studentId:integer
            name:string
            e-mail:string
            mobilePhone:string
            school:string
            major:string
            commitRecord:
              properties:
                []
      500:
        description:服务器错误



/invitation
  post:
    body:
      application/json:
        properties:
          sender:integer
          receiver:integer
          sendTime:string
          content:string
          status:integer
            description:四种状态:[0:unread,1:read,2:accepted,3:rejected]
    responses:
      201:
        body:
          application/json:
            properties:
              invitationId:integer
      500:
        description:服务器错误

/invitation/:invitationId
  put:
    body:
      application/json:
        properties:
          status:integer
            description:四种状态:[0:unread,1:read,2:accepted,3:rejected]
    responses:
      204:
        description:发送成功
      500:
        description:服务器错误

  get:
    responses:
      200:
        application/json:
          sender:integer
          receiver:integer
          sendTime:string
          content:string
          status:integer
            description:四种状态:[0:unread,1:read,2:accepted,3:rejected]
      500:
        description:服务器错误

  delete:
    responses:
      204:
        description:删除成功
