#%RAML 1.0
title: TWARecurting API
description:
version: V1
baseUri: http://api.bronzesword.com/teacher-admin-web/

/mentors:
   /{mentorMobilePhone}:
     get:
       responses:
         200:
           body:
             application/json:
              properties:
                userId: integer
                name: string
                major: string
         404:
           description: 没有这个教练
     /{mentorId}/users/{userId}:
       post:
         responses:
           201:
             description: 成功建立关系
           403:
             description: 关系已存在，拒绝执行
