#%RAML 1.0
title: TWARecurting API
description:
version: V1
baseUri: http://api.bronzesword.com/teacher-admin-web/

/mentors:
   /{email}:
     get:
       responses:
         200:
           body:
             application/json:
               properties:
                 mentorsUri:
                 properties:
                    string[]
         404:
           description: 没有这个字段

/relationshipCreating:
   /{mentorId}/users/{userId}:
       post:
         responses:
           201:
             description: 成功建立关系
           403:
             description: 关系已存在，拒绝执行
