default:
  port: 3000
  database: 'mongodb://mongo/twars'
  paperApiServer: 'http://paper-api:8080/paper-api/'
  userApiServer: 'http://user-api:8080/user-api/'
  reportCsvAppServer: 'http://192.168.99.100:8888/api/'
  appServer: 'http://web-api:3000/'
  nginxServer: 'http://nginx/fs'
  taskServer: 'http://task-queue:4000/'
  taskApi: 'http://jenkins:8080/job/HOMEWORK-SCORING/buildWithParameters'
  ballbackTaskUrl: 'http://web-api:3000/homework/scoring/'
  staticFileServer: 'http://192.168.99.100:8888/fs/'
  sessionTtl: 3600 # 60(MINUTE_PER_HOUR) * 60(SECONDS_PER_MINUTE)
  emailServer: '192.168.99.100:8888'
  emailAccount: 'twarss@163.com'
  emailPassword: 'ssww123456'
  gitHubToken: 'Basic dHdhcnM6c3cxMjM0NTY3OA=='
  QAInfoAddress: ''
development:
  database: 'mongodb://localhost/twars'
  paperApiServer: 'http://localhost:12306/'
  userApiServer: 'http://localhost:12306/'
  appServer: 'http://localhost:3000/'
  taskServer: 'http://192.168.99.100:4000/'
integration:
  paperApiServer: 'http://localhost:12306/'
  userApiServer: 'http://localhost:12306/'
  database: 'mongodb://localhost/twars'
  taskApi: 'http://localhost:12306/job/HOMEWORK-SCORING/buildWithParameters'
  nginxServer: 'http://localhost:12306/nginx'
test:
  staticFileServer: 'http://localhost/fs/'
  database: 'mongodb://mongo/twars'
  paperApiServer: 'http://paper-api:8080/paper-api/'
  userApiServer: 'http://user-api:8080/user-api/'
  appServer: 'http://localhost:3000/'
  taskServer: 'http://192.168.10.54:9090/'
  taskApi: 'http://192.168.10.54:9090/job/HOMEWORK_SCORING/buildWithParameters'
  homeworkCreationTaskApi: 'http://192.168.10.54:9090/job/ADD_HOMEWORK/buildWithParameters'
  nginxServer: 'http://localhost/fs'
  ballbackTaskUrl: 'http://192.168.10.165:3000/homework/scoring/'

production:
  staticFileServer: '/fs/'
  emailServer: 'academy.thoughtworks.cn'
  reportCsvAppServer: 'http://academy.thoughtworks.cn/api/'
